### ISSUE TITLE
day-02-drill

### ISSUE THREAD

**Issue by ben-manning** [sf-wdi-24/modules#50] opened 2015-10-29 18:23 UTC
JSON & HTML Strings Drill:

Sources:

https://github.com/sf-wdi-22-23/modules-22/tree/master/w02-working-with-objects/d3-drills
https://github.com/sf-wdi-21/notes/blob/master/week-02/drills.md

**Comment by cameronjacoby** [comment] 2015-10-31 23:24
Duplicate of issue #16?

**Closed as completed** 2015-11-02 05:08 UTC
Labels: lesson planning
