### ISSUE TITLE
day-03-mod-02

### ISSUE THREAD

**Issue by ben-manning** [sf-wdi-24/modules#52] opened 2015-10-29 18:34 UTC
Intro to OOP & JS Constructors:

Sources:

https://github.com/sf-wdi-19-20/modules/tree/master/w2_d3_1_modeling_oop
https://github.com/sf-wdi-19-20/modules/blob/master/w2_d2_1_underscore_templating/oop_prereading.md
https://github.com/sf-wdi-21/notes/tree/master/week-02/day-04-Objects-and-OOP/dawn-objects
https://github.com/sf-wdi-21/notes/blob/master/week-02/day-04-Objects-and-OOP/dawn-objects/readme.md
https://github.com/sf-wdi-21/notes/blob/master/week-02/day-04-Objects-and-OOP/dusk-object-drills/readme.md
https://github.com/sf-wdi-22-23/modules-22/tree/master/w02-working-with-objects/d2-dawn-OOP

**Comment by cameronjacoby** [comment] 2015-10-31 23:25
Duplicate of issue #22?

**Closed as completed** 2015-11-03 19:32 UTC
Labels: lesson planning
