### ISSUE TITLE
day-02-mod-01

### ISSUE THREAD

**Issue by ben-manning** [sf-wdi-24/modules#51] opened 2015-10-29 18:29 UTC
HTML Forms:

Sources:  

https://github.com/sf-wdi-21/notes/blob/master/week-02/day-02-forms%2BAJAX/dawn-forms/readme.md
https://github.com/sf-wdi-22-23/modules-22/tree/master/w02-working-with-objects/d2-homework
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/How_to_structure_an_HTML_form

**Comment by cameronjacoby** [comment] 2015-10-31 23:24
Duplicate of issue #17?

**Closed as completed** 2015-11-02 04:56 UTC
Labels: lesson planning
