### ISSUE TITLE
day-01-mod-02

### ISSUE THREAD

**Issue by ben-manning** [sf-wdi-24/modules#49] opened 2015-10-29 18:18 UTC
Javascript Iterators:

Beginning sources:

https://github.com/sf-wdi-21/notes/tree/master/week-02/day-01-arrays%2BIterators/dusk-iteratorsLab

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

https://learn.jquery.com/using-jquery-core/iterating/

**Comment by cameronjacoby** [comment] 2015-10-31 23:23
Duplicate of issue #15?

**Closed as completed** 2015-11-02 17:17 UTC
Labels: lesson planning
